### ISSUE TITLE
Vsual Studio 2019 CMake with fxc created .h files in wrong folder

### ISSUE THREAD

**Issue by lucifer602288** [tschw/AntTweakBar#2]
"2>compilation header save succeeded; see C:\Users\lucifer\Downloads\AntTweakBar-master\build\Renderer\TwDirect3D11_LineRectVS.h
2>Building Custom Rule C:/Users/lucifer/Downloads/AntTweakBar-master/Renderer/CMakeLists.txt
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): warning MSB8065: Custom build for item "C:\Users\lucifer\Downloads\AntTweakBar-master\Renderer\compile\TwDirect3D11.hlsl" succeeded, but specified output "c:\users\lucifer\downloads\anttweakbar-master\renderer\twdirect3d11_linerectvs.h" has not been created. This may cause incremental build to work incorrectly."

.h files, see below, from TwDirect3D11.hlsl with fxc are created in the path AntTweakBar-master\build\Renderer and not in AntTweakBar-master\Renderer\compile, manual copying the files to AntTweakBar-master\Renderer\compile works for compiling.
TwDirect3D11_LineRectCstColorVS.h
TwDirect3D11_LineRectPS.h
TwDirect3D11_LineRectVS.h
TwDirect3D11_TextCstColorVS.h
TwDirect3D11_TextPS.h
TwDirect3D11_TextVS.h

Please fix. I am no CMake expert.

**Comment by tschw** [comment]
Copied from the review of #3 :

This is not an error but intentional, alhough apparently bugged (missing an include directory?) and maybe we should generate those files into a subdirectory:

In my world, the source tree should always be read-only and generated code should go to somewhere in the build tree and then be added to the target. Since we're talking headers, adding them to the target is only for the IDE and the containing directory needs to be added to the list of include directories for that target too.

**Comment by tschw** [comment]
In other words, it's better to make the compiler find the files where they are generated by setting an appropriate include directory, rather than trying to generate in or copy into the source tree.

**Comment by tschw** [comment]
Looks like the include path is already set up correctly [here](https://github.com/tschw/AntTweakBar/blob/4ff73b96515164cbe66b484022e56e771ea6c224/Renderer/CMakeLists.txt#L85), so the C++ compiler should find those headers.

Can you provide complete diagnostics of the build failing OOTB?

**Comment by lucifer602288** [comment]
CMAKE updated to from version 3.17 to version 3.19. Issue disappeared.
